### ISSUE TITLE
做的真棒！

### ISSUE THREAD

**Issue by aijuzhe** [xxweimei/krpano-editor-js#2]
对我这个菜鸟帮助很大，咨询个问题，如果我要做个本地轻量的编辑器，是不是直接在krpano.editor.js里把修改数据更新到tour.xml文件里，朋友您那儿有这个操作方法的文件吗，参考学习下，刚开始研究程序

**Comment by xxweimei** [comment]
我的demo是调用接口修改服务器上的xml文件,你可以写个简单的后台实现这部分

**Comment by xxweimei** [comment]
我有空写个简单的java后台接口，上传上来吧

**Comment by aijuzhe** [comment]
非常感谢朋友！

**Comment by ROCNRAUN** [comment]
一按保存就是“系统错误”，不会用耶，楼主可以不可以教教啊，不会写简单的后台。谢谢啦

**Comment by sekibara** [comment]
界面做得很漂亮！能否先把原来服务器上的程序发上来参考一下？多谢！！
url: "http://192.168.33.125:8080/api/editor/" + encodeURIComponent(projectName) + "/save",

**Comment by aijuzhe** [comment]
@xxweimei 朋友这个对我帮助很大，你微信什么，发个红包表达下谢意！

**Comment by xxweimei** [comment]
@aijuzhe 你可以加我qq 793271105

**Comment by xxweimei** [comment]
项目更新
