### ISSUE TITLE
不明白是怎么修改了服务器上面的xml的呢？

### ISSUE THREAD

**Issue by zhuyuanwen** [xxweimei/krpano-editor-js#3]
我看了代码，编辑的部分主要是sceneList这个object，save()时候post给服务器。
可是不明白是怎么修改了服务器上面的xml的呢？
还有，下次打开的时候，应该还需要get数据才能知道编辑的结果。

**Comment by zhuyuanwen** [comment]
我没有看到有地方调用了onready()这个函数。它是什么地方被调用的？

**Comment by zhuyuanwen** [comment]
@xxweimei

**Comment by xxweimei** [comment]
你做任何变动的时候，已经在当前已经加载好的场景里面生效了，save只是落地成文件，刷新的时候能够保存而已。

**Comment by xxweimei** [comment]
onready()函数是在krpano加载的xml里面调用的，可以按照它的语法自定义一些功能，这个onready就是自定义的，目的是在krpano场景渲染完成（小行星效果结束）之后再加载编辑页面的元素。

**Comment by zhuyuanwen** [comment]
@xxweimei  onready()函数我明白了。save成落地文件我懂了，那么这样算是修改了xml文件么？还是说通过sceneList里面的数据，将index_editor.html的显示变了，xml并没有变？

**Comment by aijuzhe** [comment]
@xxweimei 是编辑完后，重新组装成tour.xml 格式，替换原来的xml文件吗？可以上传个简单的保存到本地的save方案吗，先谢谢了！

**Comment by xxweimei** [comment]
@zhuyuanwen 你在页面上执行一些krpano的操作，仅对于页面当前有效，你刷新页面的时候会重新加载xml文件内容。执行save等于修改了xml的内容，刷新后还会生效。就像你在控制台申明一个变量一样。

**Comment by xxweimei** [comment]
@aijuzhe 这个要等我有空再写，思路就是你起个后台服务提供一个web接口，save的时候调用nodejs的服务去修改xml文件。

**Comment by xxweimei** [comment]
项目更新，附带nodejs后台
